// Code generated by protoc-gen-go.
// source: webrealms.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	webrealms.proto

It has these top-level messages:
	ProtocolPacket
	ProtocolMessage
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtocolMessage_MessageType int32

const (
	ProtocolMessage_NONE       ProtocolMessage_MessageType = 0
	ProtocolMessage_HELLO      ProtocolMessage_MessageType = 13
	ProtocolMessage_CONNECT    ProtocolMessage_MessageType = 14
	ProtocolMessage_DISCONNECT ProtocolMessage_MessageType = 15
	ProtocolMessage_PING       ProtocolMessage_MessageType = 16
	ProtocolMessage_PONG       ProtocolMessage_MessageType = 17
	ProtocolMessage_SPAWN      ProtocolMessage_MessageType = 18
	ProtocolMessage_UNSPAWN    ProtocolMessage_MessageType = 19
	ProtocolMessage_POSITION   ProtocolMessage_MessageType = 20
	ProtocolMessage_ROTATION   ProtocolMessage_MessageType = 21
)

var ProtocolMessage_MessageType_name = map[int32]string{
	0:  "NONE",
	13: "HELLO",
	14: "CONNECT",
	15: "DISCONNECT",
	16: "PING",
	17: "PONG",
	18: "SPAWN",
	19: "UNSPAWN",
	20: "POSITION",
	21: "ROTATION",
}
var ProtocolMessage_MessageType_value = map[string]int32{
	"NONE":       0,
	"HELLO":      13,
	"CONNECT":    14,
	"DISCONNECT": 15,
	"PING":       16,
	"PONG":       17,
	"SPAWN":      18,
	"UNSPAWN":    19,
	"POSITION":   20,
	"ROTATION":   21,
}

func (x ProtocolMessage_MessageType) String() string {
	return proto.EnumName(ProtocolMessage_MessageType_name, int32(x))
}
func (ProtocolMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type ProtocolPacket struct {
	Message []*ProtocolMessage `protobuf:"bytes,1,rep,name=Message,json=message" json:"Message,omitempty"`
}

func (m *ProtocolPacket) Reset()                    { *m = ProtocolPacket{} }
func (m *ProtocolPacket) String() string            { return proto.CompactTextString(m) }
func (*ProtocolPacket) ProtoMessage()               {}
func (*ProtocolPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtocolPacket) GetMessage() []*ProtocolMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type ProtocolMessage struct {
	Type       ProtocolMessage_MessageType        `protobuf:"varint,1,opt,name=Type,json=type,enum=main.ProtocolMessage_MessageType" json:"Type,omitempty"`
	Sender     string                             `protobuf:"bytes,2,opt,name=Sender,json=sender" json:"Sender,omitempty"`
	Hello      *ProtocolMessage_HelloMessage      `protobuf:"bytes,13,opt,name=Hello,json=hello" json:"Hello,omitempty"`
	Connect    *ProtocolMessage_ConnectMessage    `protobuf:"bytes,14,opt,name=Connect,json=connect" json:"Connect,omitempty"`
	Disconnect *ProtocolMessage_DisconnectMessage `protobuf:"bytes,15,opt,name=Disconnect,json=disconnect" json:"Disconnect,omitempty"`
	Ping       *ProtocolMessage_PingMessage       `protobuf:"bytes,16,opt,name=Ping,json=ping" json:"Ping,omitempty"`
	Pong       *ProtocolMessage_PongMessage       `protobuf:"bytes,17,opt,name=Pong,json=pong" json:"Pong,omitempty"`
	Spawn      *ProtocolMessage_SpawnMessage      `protobuf:"bytes,18,opt,name=Spawn,json=spawn" json:"Spawn,omitempty"`
	Unspawn    *ProtocolMessage_UnspawnMessage    `protobuf:"bytes,19,opt,name=Unspawn,json=unspawn" json:"Unspawn,omitempty"`
	Position   *ProtocolMessage_PositionMessage   `protobuf:"bytes,20,opt,name=Position,json=position" json:"Position,omitempty"`
	Rotation   *ProtocolMessage_RotationMessage   `protobuf:"bytes,21,opt,name=Rotation,json=rotation" json:"Rotation,omitempty"`
}

func (m *ProtocolMessage) Reset()                    { *m = ProtocolMessage{} }
func (m *ProtocolMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtocolMessage) ProtoMessage()               {}
func (*ProtocolMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtocolMessage) GetType() ProtocolMessage_MessageType {
	if m != nil {
		return m.Type
	}
	return ProtocolMessage_NONE
}

func (m *ProtocolMessage) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ProtocolMessage) GetHello() *ProtocolMessage_HelloMessage {
	if m != nil {
		return m.Hello
	}
	return nil
}

func (m *ProtocolMessage) GetConnect() *ProtocolMessage_ConnectMessage {
	if m != nil {
		return m.Connect
	}
	return nil
}

func (m *ProtocolMessage) GetDisconnect() *ProtocolMessage_DisconnectMessage {
	if m != nil {
		return m.Disconnect
	}
	return nil
}

func (m *ProtocolMessage) GetPing() *ProtocolMessage_PingMessage {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *ProtocolMessage) GetPong() *ProtocolMessage_PongMessage {
	if m != nil {
		return m.Pong
	}
	return nil
}

func (m *ProtocolMessage) GetSpawn() *ProtocolMessage_SpawnMessage {
	if m != nil {
		return m.Spawn
	}
	return nil
}

func (m *ProtocolMessage) GetUnspawn() *ProtocolMessage_UnspawnMessage {
	if m != nil {
		return m.Unspawn
	}
	return nil
}

func (m *ProtocolMessage) GetPosition() *ProtocolMessage_PositionMessage {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *ProtocolMessage) GetRotation() *ProtocolMessage_RotationMessage {
	if m != nil {
		return m.Rotation
	}
	return nil
}

type ProtocolMessage_HelloMessage struct {
}

func (m *ProtocolMessage_HelloMessage) Reset()                    { *m = ProtocolMessage_HelloMessage{} }
func (m *ProtocolMessage_HelloMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtocolMessage_HelloMessage) ProtoMessage()               {}
func (*ProtocolMessage_HelloMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type ProtocolMessage_ConnectMessage struct {
	Username string `protobuf:"bytes,1,opt,name=Username,json=username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *ProtocolMessage_ConnectMessage) Reset()         { *m = ProtocolMessage_ConnectMessage{} }
func (m *ProtocolMessage_ConnectMessage) String() string { return proto.CompactTextString(m) }
func (*ProtocolMessage_ConnectMessage) ProtoMessage()    {}
func (*ProtocolMessage_ConnectMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 1}
}

func (m *ProtocolMessage_ConnectMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProtocolMessage_ConnectMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ProtocolMessage_DisconnectMessage struct {
}

func (m *ProtocolMessage_DisconnectMessage) Reset()         { *m = ProtocolMessage_DisconnectMessage{} }
func (m *ProtocolMessage_DisconnectMessage) String() string { return proto.CompactTextString(m) }
func (*ProtocolMessage_DisconnectMessage) ProtoMessage()    {}
func (*ProtocolMessage_DisconnectMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 2}
}

type ProtocolMessage_PingMessage struct {
}

func (m *ProtocolMessage_PingMessage) Reset()                    { *m = ProtocolMessage_PingMessage{} }
func (m *ProtocolMessage_PingMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtocolMessage_PingMessage) ProtoMessage()               {}
func (*ProtocolMessage_PingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 3} }

type ProtocolMessage_PongMessage struct {
}

func (m *ProtocolMessage_PongMessage) Reset()                    { *m = ProtocolMessage_PongMessage{} }
func (m *ProtocolMessage_PongMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtocolMessage_PongMessage) ProtoMessage()               {}
func (*ProtocolMessage_PongMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 4} }

type ProtocolMessage_SpawnMessage struct {
	Name string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *ProtocolMessage_SpawnMessage) Reset()                    { *m = ProtocolMessage_SpawnMessage{} }
func (m *ProtocolMessage_SpawnMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtocolMessage_SpawnMessage) ProtoMessage()               {}
func (*ProtocolMessage_SpawnMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 5} }

func (m *ProtocolMessage_SpawnMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProtocolMessage_UnspawnMessage struct {
}

func (m *ProtocolMessage_UnspawnMessage) Reset()         { *m = ProtocolMessage_UnspawnMessage{} }
func (m *ProtocolMessage_UnspawnMessage) String() string { return proto.CompactTextString(m) }
func (*ProtocolMessage_UnspawnMessage) ProtoMessage()    {}
func (*ProtocolMessage_UnspawnMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 6}
}

type ProtocolMessage_PositionMessage struct {
	X float32 `protobuf:"fixed32,1,opt,name=X,json=x" json:"X,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=Y,json=y" json:"Y,omitempty"`
}

func (m *ProtocolMessage_PositionMessage) Reset()         { *m = ProtocolMessage_PositionMessage{} }
func (m *ProtocolMessage_PositionMessage) String() string { return proto.CompactTextString(m) }
func (*ProtocolMessage_PositionMessage) ProtoMessage()    {}
func (*ProtocolMessage_PositionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 7}
}

func (m *ProtocolMessage_PositionMessage) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ProtocolMessage_PositionMessage) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type ProtocolMessage_RotationMessage struct {
	X float32 `protobuf:"fixed32,1,opt,name=X,json=x" json:"X,omitempty"`
}

func (m *ProtocolMessage_RotationMessage) Reset()         { *m = ProtocolMessage_RotationMessage{} }
func (m *ProtocolMessage_RotationMessage) String() string { return proto.CompactTextString(m) }
func (*ProtocolMessage_RotationMessage) ProtoMessage()    {}
func (*ProtocolMessage_RotationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 8}
}

func (m *ProtocolMessage_RotationMessage) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtocolPacket)(nil), "main.ProtocolPacket")
	proto.RegisterType((*ProtocolMessage)(nil), "main.ProtocolMessage")
	proto.RegisterType((*ProtocolMessage_HelloMessage)(nil), "main.ProtocolMessage.HelloMessage")
	proto.RegisterType((*ProtocolMessage_ConnectMessage)(nil), "main.ProtocolMessage.ConnectMessage")
	proto.RegisterType((*ProtocolMessage_DisconnectMessage)(nil), "main.ProtocolMessage.DisconnectMessage")
	proto.RegisterType((*ProtocolMessage_PingMessage)(nil), "main.ProtocolMessage.PingMessage")
	proto.RegisterType((*ProtocolMessage_PongMessage)(nil), "main.ProtocolMessage.PongMessage")
	proto.RegisterType((*ProtocolMessage_SpawnMessage)(nil), "main.ProtocolMessage.SpawnMessage")
	proto.RegisterType((*ProtocolMessage_UnspawnMessage)(nil), "main.ProtocolMessage.UnspawnMessage")
	proto.RegisterType((*ProtocolMessage_PositionMessage)(nil), "main.ProtocolMessage.PositionMessage")
	proto.RegisterType((*ProtocolMessage_RotationMessage)(nil), "main.ProtocolMessage.RotationMessage")
	proto.RegisterEnum("main.ProtocolMessage_MessageType", ProtocolMessage_MessageType_name, ProtocolMessage_MessageType_value)
}

func init() { proto.RegisterFile("webrealms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x5f, 0xaf, 0xd2, 0x3e,
	0x1c, 0xc6, 0x7f, 0xe3, 0x37, 0x60, 0x7c, 0x81, 0x6d, 0x94, 0x83, 0x59, 0x76, 0x23, 0x12, 0x8d,
	0xdc, 0x88, 0x09, 0xc6, 0xc4, 0x2b, 0x13, 0xc2, 0x21, 0x40, 0x72, 0xec, 0x96, 0x01, 0x51, 0x2f,
	0x77, 0xa0, 0xc1, 0x45, 0x68, 0x97, 0x75, 0x27, 0xc8, 0x2b, 0xf0, 0xdd, 0xf8, 0x1a, 0x4d, 0xbb,
	0x8e, 0x7f, 0x72, 0xb8, 0xa2, 0x9f, 0xf6, 0x79, 0x9e, 0x96, 0xa7, 0x05, 0xb0, 0x76, 0xe4, 0x31,
	0x21, 0xe1, 0x66, 0xcb, 0x7b, 0x71, 0xc2, 0x52, 0x86, 0xf4, 0x6d, 0x18, 0xd1, 0xce, 0x00, 0x4c,
	0x5f, 0xe0, 0x92, 0x6d, 0xfc, 0x70, 0xf9, 0x93, 0xa4, 0xe8, 0x3d, 0x94, 0xbf, 0x10, 0xce, 0xc3,
	0x35, 0x71, 0xb4, 0xf6, 0xff, 0xdd, 0x6a, 0xbf, 0xd5, 0x13, 0xca, 0x5e, 0x2e, 0x53, 0x8b, 0x41,
	0x79, 0x9b, 0x0d, 0x3a, 0x7f, 0x0c, 0xb0, 0x2e, 0x16, 0xd1, 0x47, 0xd0, 0xe7, 0xfb, 0x58, 0x24,
	0x68, 0x5d, 0xb3, 0xff, 0xea, 0x6a, 0x42, 0x4f, 0x7d, 0x0a, 0x61, 0xa0, 0xa7, 0xfb, 0x98, 0xa0,
	0x17, 0x50, 0x9a, 0x11, 0xba, 0x22, 0x89, 0x53, 0x68, 0x6b, 0xdd, 0x4a, 0x50, 0xe2, 0x92, 0xd0,
	0x27, 0x28, 0x4e, 0xc8, 0x66, 0xc3, 0x9c, 0x7a, 0x5b, 0xeb, 0x56, 0xfb, 0x9d, 0xeb, 0x79, 0x52,
	0x92, 0x1f, 0xaf, 0xf8, 0x43, 0x10, 0xfa, 0x0c, 0xe5, 0x21, 0xa3, 0x94, 0x2c, 0x53, 0xc7, 0x94,
	0xde, 0xd7, 0xd7, 0xbd, 0x4a, 0x74, 0xf8, 0x72, 0xcb, 0x8c, 0xd1, 0x18, 0xe0, 0x3e, 0xe2, 0x8a,
	0x1c, 0x4b, 0x46, 0xbc, 0xbd, 0x1e, 0x71, 0xd4, 0xe5, 0x29, 0xb0, 0x3a, 0x4c, 0x89, 0x46, 0xfc,
	0x88, 0xae, 0x1d, 0x5b, 0x46, 0x3c, 0xd3, 0x88, 0x50, 0xe4, 0x66, 0x3d, 0x8e, 0xe8, 0x5a, 0xda,
	0x18, 0x5d, 0x3b, 0x8d, 0x9b, 0x36, 0x76, 0x6a, 0x63, 0x74, 0x2d, 0x0a, 0x9b, 0xc5, 0xe1, 0x8e,
	0x3a, 0xe8, 0x56, 0x61, 0x52, 0x72, 0x28, 0x8c, 0x0b, 0x12, 0x85, 0x2d, 0xa8, 0x1c, 0x3a, 0xcd,
	0x5b, 0x85, 0x29, 0xd1, 0xa1, 0xb0, 0xa7, 0x8c, 0xd1, 0x00, 0x0c, 0x9f, 0xf1, 0x28, 0x8d, 0x18,
	0x75, 0xee, 0x64, 0xc0, 0x9b, 0xe7, 0x0e, 0x9d, 0xa9, 0xf2, 0x04, 0x23, 0x56, 0x13, 0x22, 0x22,
	0x60, 0x69, 0x28, 0x23, 0x5a, 0xb7, 0x22, 0x72, 0xd5, 0x21, 0x22, 0x51, 0x13, 0xae, 0x09, 0xb5,
	0xd3, 0xd7, 0xe0, 0x4e, 0xc0, 0x3c, 0xbf, 0x61, 0xe4, 0x82, 0xb1, 0xe0, 0x24, 0xa1, 0xe1, 0x36,
	0x7b, 0xa5, 0x95, 0xc0, 0x78, 0x52, 0x2c, 0xd6, 0xfc, 0x90, 0xf3, 0x1d, 0x4b, 0x56, 0xea, 0x21,
	0x1a, 0xb1, 0x62, 0xb7, 0x09, 0x8d, 0x7f, 0x2e, 0xda, 0xad, 0x43, 0xf5, 0xe4, 0xea, 0x24, 0x1e,
	0xaf, 0xc4, 0xed, 0x40, 0xed, 0xb4, 0x69, 0x84, 0x40, 0xc7, 0xc7, 0x6d, 0x75, 0xb1, 0xa5, 0x6b,
	0x83, 0x79, 0xde, 0xa8, 0xfb, 0x0e, 0xac, 0x8b, 0x8a, 0x50, 0x0d, 0xb4, 0x6f, 0xd2, 0x55, 0x08,
	0xb4, 0x5f, 0x82, 0xbe, 0xcb, 0xe3, 0x15, 0x02, 0x6d, 0xef, 0xbe, 0x04, 0xeb, 0xa2, 0x8e, 0x73,
	0x79, 0xe7, 0xb7, 0x06, 0xd5, 0x93, 0x5f, 0x1c, 0x32, 0x40, 0xc7, 0x1e, 0x1e, 0xd9, 0xff, 0xa1,
	0x0a, 0x14, 0x27, 0xa3, 0x87, 0x07, 0xcf, 0xae, 0xa3, 0x2a, 0x94, 0x87, 0x1e, 0xc6, 0xa3, 0xe1,
	0xdc, 0x36, 0x91, 0x09, 0x70, 0x3f, 0x9d, 0xe5, 0x6c, 0x09, 0x87, 0x3f, 0xc5, 0x63, 0xdb, 0x96,
	0x23, 0x0f, 0x8f, 0xed, 0x86, 0xf0, 0xce, 0xfc, 0xc1, 0x57, 0x6c, 0x23, 0xe1, 0x5d, 0xe0, 0x0c,
	0x9a, 0xa8, 0x06, 0x86, 0xef, 0xcd, 0xa6, 0xf3, 0xa9, 0x87, 0xed, 0x3b, 0x41, 0x81, 0x37, 0x1f,
	0x48, 0x6a, 0x3d, 0x96, 0xe4, 0x1f, 0xd0, 0x87, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x25, 0xc9,
	0xe1, 0x5d, 0x93, 0x04, 0x00, 0x00,
}
